branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - { name: "beta", prerelease: true }
  - { name: "alpha", prerelease: true }

plugins:
  # Determine the type of release by analyzing commits.
  # ie: Major, Minor or Patch
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - { breaking: true, release: major }
        - { revert: true, release: patch }
        - { type: feat, release: minor }
        - { type: fix, release: patch }
        - { type: chore, release: patch }
        - { type: style, release: patch }
        - { type: perf, release: patch }
        - { type: docs, release: patch }
        - { type: refactor, release: patch }
        - { type: build, release: patch }
        - { type: ci, release: patch }
        - { type: test, release: patch }
        - { type: update, release: patch }

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        # spec: https://github.com/conventional-changelog/conventional-changelog-config-spec/tree/master/versions/2.1.0
        types:
          - { type: feat, section: "Features" }
          - { type: fix, section: "Bug Fixes" }
          - { type: chore, section: "Misc" }
          - { type: docs, section: "Misc" }
          - { type: style, section: "Improvements" }
          - { type: refactor, section: "Improvements" }
          - { type: perf, section: "Improvements" }
          - { type: test, section: "Automation" }
          - { type: ci, section: "Automation" }
          - { type: build, section: "Automation" }
          - { type: update, section: "Automation" }

  # Write version to VERSION.txt
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"

  # Create new github release
  - "@semantic-release/github"