services:
  browser:
    image: chromedp/headless-shell
    ports:
      - "9222:9222"
    command: [
      "--no-sandbox",
      "--disable-gpu",
      "--remote-debugging-address=0.0.0.0",
      "--remote-debugging-port=9222",
      "--disable-extensions",
      "--enable-automation",
      "--disable-blink-features=AutomationControlled",
      "--incognito",
      "--user-agent=Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
    ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHROME_HOST: browser
      CHROME_PORT: 9222
    ports:
      - "8080:8080"
    depends_on:
      - browser
    links:
      - browser