name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Build checks
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ 1.23.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - run: go version

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run go fmt
        run: go fmt ./...

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --verbose
          skip-cache: true

      - name: Run tests and collect coverage
        run: go test -v -race -cover ./... -count=1 -coverprofile=coverage.out -covermode=atomic

      - name: Run benchmarks
        run: go test -bench=. -benchtime=1s -benchmem -cpu=1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run go build
        run: go build ./...