name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        type: string
        default: "latest"
        required: true
  workflow_call:
    inputs:
      tag:
        description: "Tag to publish"
        type: string
        default: "latest"
        required: true

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nightcodezero/katsini:latest
            ghcr.io/nightcodezero/katsini:${{ inputs.tag }}
            ghcr.io/nightcodezero/katsini:${{ github.sha }}