name: Release and publish

on:
  workflow_dispatch:

jobs:
  fetch-version:
    name: Fetch version and release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fetch-version.outputs.tag }}
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull latest changes and reset to latest commit
        shell: bash
        run: git pull --no-commit && git reset --hard HEAD

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install @semantic-release/github @semantic-release/exec conventional-changelog-conventionalcommits@8

      - name: Run semantic release
        run: npx semantic-release --debug true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch version
        id: fetch-version
        run: echo "tag=$(cat VERSION.txt)" >> $GITHUB_OUTPUT

  publish:
    name: Publish to Github Packages Registry
    needs: fetch-version
    if: needs.fetch-version.outputs.tag
    uses: ./.github/workflows/publish.yml
    with:
      tag: ${{ needs.fetch-version.outputs.tag }}
